-- This init file contains all of my plugin configs
require("plugins.colors")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.fugitive")
require("plugins.lsp")
require("plugins.lualine")
require("plugins/nvimtree")
require("plugins/commenter")
require("plugins/todocomments")
